# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CloudFlare
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm ci

      - name: Build
        env:
          VITE_R2_BUCKET_URL: ${{ secrets.R2_BUCKET_API_ENDPOINT }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name="fo76-gather"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Create Recipes Directory in R2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -X PUT "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com/${{ secrets.R2_BUCKET_NAME }}/recipes/" \
          -H "Authorization: AWS4-HMAC-SHA256 Credential=${{ secrets.R2_READWRITE_ACCESS_KEY_ID }}" \
          -H "x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" \
          -H "x-amz-date: $(date -u +%Y%m%dT%H%M%SZ)"
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_READWRITE_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_READWRITE_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }} 